### ISSUE TITLE
RFC: Add single github button

### ISSUE THREAD

**Issue by phillysnow** [prismicio/sm-documentation#7]
We have to replace the star and fork github buttons in the main menu with a single github button.

**Comment by Dragana-Trgovcevic** [comment]
![image](https://user-images.githubusercontent.com/59695671/93467874-7eb64200-f8ee-11ea-9602-62aac65d3c26.png)

design here: https://www.figma.com/file/ON2XaerBkty0Dk3fj58OQf/Slice-Machine?node-id=1618%3A5731
